resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/56fadcea03417771f4b3666fd1dfc9bad8df1484/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: e22be186e0b1018260ed7c5166871f82a869b94d
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-base
    commit: 0e26a4f00324100b4c34f2a9c7606ae03e94d7a2
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: db1c822f1847e40eb340152b95ab3138a10f92df
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 56fadcea03417771f4b3666fd1dfc9bad8df1484
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 18906dd8c109380c4b1fa20ed35100e48135aac3

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: 43a036c5bbe68ca2e9cbe611eab7982e2348fe49

  - bimap-0.4.0
  - binary-0.8.7.0
  - time-units-1.0.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - prometheus-2.1.1
  - containers-0.5.11.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1

  # Windows only
  - Win32-2.5.4.1

nix:
  shell-file: nix/stack-shell.nix
