resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/b83730dccab14111d62144b048084eec7900d091/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: c85d57a95d919336afea7e0eff00e834bd6b4b58
    subdirs:
      - contra-tracer
      - iohk-monitoring

  - git: https://github.com/input-output-hk/cardano-base
    commit: 31aafc8d5c090c4443a12d588c923badac929843
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: 291bb7a169363ac67ba0bf401973491f6a3be84f
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: b83730dccab14111d62144b048084eec7900d091
    subdirs:
      - .
      - test

  - git: https://github.com/input-output-hk/cardano-shell
    commit: 3664336312b064f30530be003c09cbe9de45df1a

  - git: https://github.com/input-output-hk/cardano-sl-x509
    commit: ec96c64c665b741c17b4e38f611315bae9b0b054

  - bimap-0.4.0
  - binary-0.8.7.0
  - time-units-1.0.0
  - ekg-prometheus-adapter-0.1.0.4
  - generic-monoid-0.1.0.0
  - prometheus-2.1.1
  - containers-0.5.11.0
  - graphviz-2999.20.0.3@sha256:cde383c356bc41136ed53cd27e0800f46dbd2185600dd0de18d66d5c49739d94
  - quickcheck-state-machine-0.6.0@sha256:3e4f8df0f6b5d415e3c8840dc75034a63e37f56f5f8cfa1035ded16345235ac4
  - splitmix-0.0.2
  - libsystemd-journal-1.4.4
  - tasty-hedgehog-1.0.0.1

  # Windows only
  - Win32-2.5.4.1

nix:
  shell-file: nix/stack-shell.nix
