steps:

  - label:   'slow ThreadNet tests'
    command: '.buildkite/slow-ThreadNet-tests.sh'
    agents:
      system: x86_64-linux

  - label:   'validate mainnet'
    command: '.buildkite/validate-mainnet.sh'
    agents:
      system: x86_64-linux
