steps:
  - label: 'hydra-eval-errors'
    command: 'nix-build ./nix -A iohkNix.hydraEvalErrors && ./result/bin/hydra-eval-errors.py'
    agents:
      system: x86_64-linux

  - label: Check dependencies tags (ie. commits) in cabal.project are present on master branches
    commands:
      - "nix build -f ./nix iohkNix.checkRepoTagsOnMasterBranches --arg src ./. --show-trace"
    agents:
      system: x86_64-linux

  - label: 'stack rebuild'
    env:
      STACK_ROOT: "/build/ouroroboros-network.stack"
    command:
      - "rm -rf /build/ouroroboros-network"
      - "cp -R . /build/ouroroboros-network"
      - "cd /build/ouroroboros-network"
      - "nix-build scripts/buildkite -o stack-rebuild"
      - "./stack-rebuild"
    branches: master
    agents:
      system: x86_64-linux

  - label: 'stack-cabal-sync'
    command: 'nix-shell ./nix -A iohkNix.stack-cabal-sync-shell --run scripts/buildkite/stack-cabal-sync.sh'
    agents:
      system: x86_64-linux

  - label: 'check-cabal-project'
    command: 'nix-build ./nix -A iohkNix.checkCabalProject -o check-cabal-project.sh && ./check-cabal-project.sh'
    agents:
      system: x86_64-linux
