name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.6.5", "8.10.2"]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Select build directory
      run: |
        if [ "$OS" == Windows_NT ]; then
          CABAL_BUILDDIR="D:\\a\\_temp\\dist"
        else
          CABAL_BUILDDIR="dist-newstyle"
        fi

        echo "CABAL_BUILDDIR=$CABAL_BUILDDIR"
        echo "CABAL_BUILDDIR=$CABAL_BUILDDIR" >> $GITHUB_ENV

    - name: Install pkgconfiglite
      if: matrix.os == 'windows-latest'
      run: choco install -y pkgconfiglite

    - name: Install libsodium
      if: matrix.os == 'windows-latest'
      run: |
        curl -Ls https://download.libsodium.org/libsodium/releases/libsodium-1.0.18-mingw.tar.gz -o libsodium-1.0.18-mingw.tar.gz
        tar zxvf libsodium-1.0.18-mingw.tar.gz

        sed -i "s|/d/a/1/s/|D:/a/cardano-node/cardano-node/|g" libsodium-win64/lib/pkgconfig/libsodium.pc

        export PKG_CONFIG_PATH="$(readlink -f libsodium-win64/lib/pkgconfig)"
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV

        export LIBSODIUM_PATH="$(readlink -f libsodium-win64/bin | sed 's|^/d|D:|g' | tr / '\\')"
        echo "LIBSODIUM_PATH=$LIBSODIUM_PATH"
        echo "$LIBSODIUM_PATH" >> $GITHUB_PATH

    - name: Install libsodium
      if: matrix.os == 'macos-latest'
      run: brew install libsodium

    - name: Configure to use libsodium
      run: |
        cat >> cabal.project <<EOF
        package cardano-crypto-praos
          flags: -external-libsodium-vrf
        EOF

    - uses: actions/setup-haskell@v1
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2.0.0'

    - name: Patch GHC 8.10.2 linker
      if: matrix.os == 'windows-latest' && matrix.ghc == '8.10.2'
      run: |
        sed -i \
          's|C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe|C:/ProgramData/chocolatey/lib/ghc.8.10.2/tools/ghc-8.10.2/mingw/bin/ld.exe|g' \
          C:/ProgramData/chocolatey/lib/ghc.8.10.2/tools/ghc-8.10.2/lib/settings

    - name: Install build environment
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get -y install libsodium23 libsodium-dev
        sudo apt-get -y install libsystemd0 libsystemd-dev
        sudo apt-get -y remove --purge software-properties-common
        sudo apt-get -y autoremove

    - name: Cabal config
      run: |
        cabal user-config init -a "http-transport: plain-http" -a "store-dir: C:\\SR" -f -v3

    - name: Set up temp directory
      run: |
        echo 'TMPDIR=${{ runner.temp }}'  >> $GITHUB_ENV
        echo 'TMP=${{ runner.temp }}'     >> $GITHUB_ENV

    # Cache cabal-store
    - name: cache cabal store
      uses: actions/cache@v1
      with:
        path: C:\SR
        key: cabal-store-8.10.2
    # Cache parts of dist-newstyle (C:\dist)
    - name: cache buiddir [cache]
      uses: actions/cache@v1
      with:
        path: C:\dist\cache
        key: dist-cache
    - name: cache buiddir [src]
      uses: actions/cache@v1
      with:
        path: C:\dist\src
        key: dist-src
    - name: cache builddir [packagedb]
      uses: actions/cache@v1
      with:
        path: C:\dist\packagedb
        key: dist-packagedb

    - name: update Hackage index
      run: cabal v2-update

    # checkout repository
    - name: checkout ouroboros-network repository
      uses: actions/checkout@v2

    - name: Use cabal.project.local.windows
      run: cp ./cabal.project.local.ci.windows ./cabal.project.local

    #
    # Build & Test network packages
    #

    # Win32-network
    - name: Win32-network [dependencies]
      if: matrix.os == 'windows-latest'
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies Win32-network

    - name: Win32-network [build]
      if: matrix.os == 'windows-latest'
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build Win32-network

    - name: Win32-network [test]
      if: matrix.os == 'windows-latest'
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-Win32-network

    # ntp-client
    - name: ntp-client [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build ntp-client

    - name: ntp-client [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build ntp-client

    - name: ntp-client [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-ntp-client


    # io-sim-classes
    - name: io-sim-classes [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies io-sim-classes

    - name: io-sim-classes [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build io-sim-classes


    # io-sim
    - name: io-sim [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies io-sim

    - name: io-sim [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build io-sim

    - name: io-sim [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-sim


    # typed-protocols
    - name: typed-protcols [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies typed-protocols

    - name: typed-protocols [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build typed-protocols


    # typed-protocols-examples
    - name: typed-protocols-examples [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies typed-protocols-examples

    - name: typed-protocols-examples [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build typed-protocols-examples

    - name: typed-protocols-examples [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run typed-protocols-tests


    # network-mux
    - name: network-mux [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies network-mux

    - name: network-mux [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build network-mux

    - name: network-mux [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-network-mux


    # ouroboros-network-framework
    - name: ouroboros-network-framework [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies ouroboros-network-framework

    - name: ouroboros-network-framework [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build ouroboros-network-framework

    # issue: #1818
    - name: ourobors-network-framework [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run ouroboros-network-framework-tests -- -p '$0 != "typed-protocols.Socket.socket send receive IPv4"' 


    # ouroboros-network
    - name: ouroboros-network [dependencies]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build --only-dependencies ouroboros-network

    - name: ouroboros-network [build]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-build ouroboros-network

    - name: ouroboros-network [test]
      run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-network

    # TODO: we need to install the cddl tool
    # - name: ouroboros-network [cddl]
    #   run: cabal --builddir="$CABAL_BUILDDIR" v2-run test-cddl
